name: Deploy to OVH via ovh-deploy branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Add .htaccess
        run: |
          echo '<IfModule mod_rewrite.c>
          RewriteEngine On
          RewriteBase /
          RewriteRule ^index\.html$ - [L]
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /index.html [L]
          </IfModule>' > dist/.htaccess

      - name: Deploy to ovh-deploy branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: ovh-deploy
          folder: dist
          clean: true
